"""Generated closure views, English and Arabic from one dataset.

Both languages render from the same canonical payload, so they can never
diverge. Views are regenerated from data; no table is maintained by hand.
An empty view is written as an explicitly empty state, never omitted.
"""

from __future__ import annotations

from pathlib import Path

from atlas.intake.store import atomic_write_json

GENERATED_MARKER_EN = (
    "<!-- GENERATED BY THE ATLAS CLOSURE PIPELINE - DO NOT EDIT BY HAND. "
    "Regenerate via `atlas closure views --apply`. -->"
)
GENERATED_MARKER_AR = (
    "مولّد آلياً بواسطة خط أنابيب الإغلاق - لا تُحرَّر يدوياً. "
    "أعد التوليد عبر `atlas closure views --apply`. -->"
)

CLOSURE_VIEW_TITLES = {
    "core-set": (
        "Core Recommendation Set",
        "مجموعة التوصيات الأساسية",
    ),
    "evidence-gap": (
        "Core Evidence Gap Matrix",
        "مصفوفة فجوات الأدلة الأساسية",
    ),
    "tier-readiness": (
        "Tier Readiness (4 / 8 / 12 / 16 GB)",
        "جاهزية الفئات (4 / 8 / 12 / 16 غيغابايت)",
    ),
    "vram-evidence": (
        "External VRAM Evidence",
        "أدلة الذاكرة الرسومية الخارجية",
    ),
    "quant-retention": (
        "Quantization Retention",
        "الاحتفاظ عند التكميم",
    ),
}

_EMPTY_EN = (
    "_No entries: Atlas found no defensible evidence for this view yet. An empty view is an "
    "honest state, not an error._"
)
_EMPTY_AR = (
    "_لا توجد عناصر: لم يعثر أطلس على دليل قابل للدفاع عنه في هذا العرض بعد. العرض الفارغ "
    "حالة صادقة وليس خطأ._"
)

STATE_LABELS_EN = {
    "STRICT_READY": "STRICT_READY",
    "CANDIDATE_READY": "CANDIDATE_READY",
    "CATALOG_ONLY": "CATALOG_ONLY",
    "BLOCKED": "BLOCKED",
}
STATE_LABELS_AR = {
    "STRICT_READY": "جاهز تمامًا",
    "CANDIDATE_READY": "جاهز كمرشح",
    "CATALOG_ONLY": "دليل الفهرسة فقط",
    "BLOCKED": "محظور",
}

STATUS_LABELS_AR = {
    "present": "متوفر",
    "missing": "مفقود",
    "refused": "مرفوض",
}


def _header_en(title: str) -> list[str]:
    return [
        GENERATED_MARKER_EN,
        f"# {title}",
        "",
        "> Derived from canonical closure records. Missing evidence is reported as",
        "> unknown; popularity, size, recency, parameter count and publisher brand never",
        "> influence these views.",
        "",
    ]


def _header_ar(title: str) -> list[str]:
    return [
        GENERATED_MARKER_AR,
        f"# {title}",
        "",
        "> مشتق من سجلات الإغلاق القانونية. يُبلَّغ عن الأدلة الناقصة كـ",
        "> «غير معروف»؛ أما الشعبية والحجم وحداثة الإصدار وعدد المعاملات واسم الناشر فلا",
        "> تؤثر إطلاقاً في هذه العروض.",
        "",
    ]


def _escape(value: object) -> str:
    return str(value if value is not None else "-").replace("|", "/")


def render_core_set_en(*, payload: dict) -> str:
    """Render the Core Recommendation Set table in English."""
    lines = _header_en(CLOSURE_VIEW_TITLES["core-set"][0])
    rows = payload.get("entries", [])
    if not rows:
        lines.extend([_EMPTY_EN, ""])
        return "\n".join(lines)
    lines.append("| Candidate | Model | Artifact | Quant | Target tiers | Readiness |")
    lines.append("|---|---|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| `{_escape(row['candidate_id'])}` | `{_escape(row['model_id'])}` | "
            f"`{_escape(row['artifact_set_id'])}` | {_escape(row.get('quantization_label'))} | "
            f"{_escape(row.get('target_tiers'))} | "
            f"{STATE_LABELS_EN.get(str(row.get('readiness_state')), 'unknown')} |"
        )
    lines.extend(["", "_Generated from canonical machine-readable records._", ""])
    return "\n".join(lines)


def render_core_set_ar(*, payload: dict) -> str:
    """Render the Core Recommendation Set table in Arabic."""
    lines = _header_ar(CLOSURE_VIEW_TITLES["core-set"][1])
    rows = payload.get("entries", [])
    if not rows:
        lines.extend([_EMPTY_AR, ""])
        return "\n".join(lines)
    lines.append("| المرشّح | النموذج | المُخرَج | التكميم | الفئات المستهدفة | الحالة |")
    lines.append("|---|---|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| `{_escape(row['candidate_id'])}` | `{_escape(row['model_id'])}` | "
            f"`{_escape(row['artifact_set_id'])}` | {_escape(row.get('quantization_label'))} | "
            f"{_escape(row.get('target_tiers'))} | "
            f"{STATE_LABELS_AR.get(str(row.get('readiness_state')), 'غير معروف')} |"
        )
    lines.extend(["", "_مولَّد من سجلات قانونية قابلة للقراءة آلياً._", ""])
    return "\n".join(lines)


def _axis_row(*, gates: dict, row: dict) -> str:
    """Second half of an evidence-gap row: quality, VRAM, retention, axes."""
    quality_status = _escape(gates.get("independent_multi_source_quality", {}).get("status"))
    vram_status = _escape(gates.get("vram_fit_state_strict", {}).get("status"))
    retention_gate = _escape(
        gates.get("quant_retention_when_post_training_quantized", {}).get("status")
    )

    def axis(value: object) -> str:
        return _escape(value) if value else "unknown"

    return (
        f"| | {quality_status} | {vram_status} | {retention_gate} | "
        f"{axis(row.get('general_quality'))} | {axis(row.get('coding_quality'))} | "
        f"{axis(row.get('reasoning_quality'))} | {_escape(row.get('strict_tiers'))} |"
    )


def render_gap_matrix_en(*, payload: dict) -> str:
    """Render the Core evidence-gap matrix in English."""
    lines = _header_en(CLOSURE_VIEW_TITLES["evidence-gap"][0])
    rows = payload.get("rows", [])
    if not rows:
        lines.extend([_EMPTY_EN, ""])
        return "\n".join(lines)
    lines.append("| Candidate | Identity | Provenance | License | Architecture | Runtime |")
    lines.append("|---|---|---|---|---|---|")
    lines.append("| | Quality | VRAM | Retention | General | Coding | Reasoning | Strict tier |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for row in rows:
        gates = row.get("gates", {})
        lines.append(
            f"| `{_escape(row['candidate_id'])}` | "
            f"{_escape(gates.get('exact_artifact_identity', {}).get('status'))} | "
            f"{_escape(gates.get('current_provenance_persisted', {}).get('status'))} | "
            f"{_escape(gates.get('license_status_acceptable', {}).get('status'))} | "
            f"{_escape(row.get('architecture_family'))} | "
            f"{_escape(gates.get('runtime_compatibility_documented', {}).get('status'))} |"
        )
        lines.append(_axis_row(gates=gates, row=row))
    lines.extend(["", "_Generated from canonical machine-readable records._", ""])
    return "\n".join(lines)


def render_gap_matrix_ar(*, payload: dict) -> str:
    """Render the Core evidence-gap matrix in Arabic."""
    lines = _header_ar(CLOSURE_VIEW_TITLES["evidence-gap"][1])
    rows = payload.get("rows", [])
    if not rows:
        lines.extend([_EMPTY_AR, ""])
        return "\n".join(lines)
    lines.append("| المرشّح | الهوية | المُصدر الحالي | الترخيص | البنية | وقت التشغيل |")
    lines.append("|---|---|---|---|---|---|")
    lines.append(
        "| | الجودة | الذاكرة الرسومية | الاحتفاظ | عام | برمجة | استدلال | الفئة الصارمة |"
    )
    lines.append("|---|---|---|---|---|---|---|---|")
    for row in rows:
        gates = row.get("gates", {})

        def status(name: str, gates: dict = gates) -> str:
            return STATUS_LABELS_AR.get(str(gates.get(name, {}).get("status")), "غير معروف")

        lines.append(
            f"| `{_escape(row['candidate_id'])}` | {status('exact_artifact_identity')} | "
            f"{status('current_provenance_persisted')} | "
            f"{status('license_status_acceptable')} | {_escape(row.get('architecture_family'))} | "
            f"{status('runtime_compatibility_documented')} |"
        )
        lines.append(_axis_row(gates=gates, row=row).replace("unknown", "غير معروف"))
    lines.extend(["", "_مولَّد من سجلات قانونية قابلة للقراءة آلياً._", ""])
    return "\n".join(lines)


def render_tier_readiness_en(*, payload: dict) -> str:
    """Render the tier readiness matrix in English."""
    lines = _header_en(CLOSURE_VIEW_TITLES["tier-readiness"][0])
    matrix = payload.get("tier_matrix", {})
    if not matrix:
        lines.extend([_EMPTY_EN, ""])
        return "\n".join(lines)
    lines.append(
        "| Tier | Core candidates | STRICT_READY | CANDIDATE_READY | CATALOG_ONLY | BLOCKED |"
    )
    lines.append("|---|---|---|---|---|---|")
    for tier in ("4", "8", "12", "16"):
        row = matrix.get(tier, {})
        lines.append(
            f"| {tier}GB | {_escape(row.get('core_candidates_in_tier'))} | "
            f"{_escape(row.get('STRICT_READY'))} | {_escape(row.get('CANDIDATE_READY'))} | "
            f"{_escape(row.get('CATALOG_ONLY'))} | {_escape(row.get('BLOCKED'))} |"
        )
    lines.extend(["", "### Top blocking evidence types", ""])
    for tier in ("4", "8", "12", "16"):
        row = matrix.get(tier, {})
        blocking = row.get("top_blocking_gates") or []
        text = ", ".join(f"{b['gate']} ({b['candidates']})" for b in blocking) or "none"
        lines.append(f"- {tier}GB: {text}")
    lines.extend(["", "_Generated from canonical machine-readable records._", ""])
    return "\n".join(lines)


def render_tier_readiness_ar(*, payload: dict) -> str:
    """Render the tier readiness matrix in Arabic."""
    lines = _header_ar(CLOSURE_VIEW_TITLES["tier-readiness"][1])
    matrix = payload.get("tier_matrix", {})
    if not matrix:
        lines.extend([_EMPTY_AR, ""])
        return "\n".join(lines)
    lines.append(
        "| الفئة | مرشّحو المجموعة الأساسية | جاهز تمامًا | جاهز كمرشّح | في الفهرس فقط | محظور |"
    )
    lines.append("|---|---|---|---|---|---|")
    for tier in ("4", "8", "12", "16"):
        row = matrix.get(tier, {})
        lines.append(
            f"| {tier} غ.ب | {_escape(row.get('core_candidates_in_tier'))} | "
            f"{_escape(row.get('STRICT_READY'))} | {_escape(row.get('CANDIDATE_READY'))} | "
            f"{_escape(row.get('CATALOG_ONLY'))} | {_escape(row.get('BLOCKED'))} |"
        )
    lines.extend(["", "### أهم أنواع الأدلة المعيقة", ""])
    for tier in ("4", "8", "12", "16"):
        row = matrix.get(tier, {})
        blocking = row.get("top_blocking_gates") or []
        text = "، ".join(f"{b['gate']} ({b['candidates']})" for b in blocking) or "لا يوجد"
        lines.append(f"- {tier} غ.ب: {text}")
    lines.extend(["", "_مولَّد من سجلات قانونية قابلة للقراءة آلياً._", ""])
    return "\n".join(lines)


def render_vram_en(*, payload: dict) -> str:
    """Render external VRAM evidence coverage in English."""
    lines = _header_en(CLOSURE_VIEW_TITLES["vram-evidence"][0])
    lines.append(f"- External measurements stored: {_escape(payload.get('measurement_count'))}")
    lines.append(
        "- Core artifacts with an external measurement: "
        f"{_escape(payload.get('core_artifacts_with_external_measurement'))}"
    )
    classes = payload.get("source_class_counts", {})
    lines.append(f"- Measurements by source class: {_escape(classes)}")
    lines.append("")
    lines.append(_EMPTY_EN if not payload.get("core_artifacts_with_external_measurement") else "")
    lines.extend(
        [
            "Atlas performs no measurement and never relabels a larger-GPU observation as",
            "verification on the target tier's hardware.",
            "",
        ]
    )
    return "\n".join(lines)


def render_vram_ar(*, payload: dict) -> str:
    """Render external VRAM evidence coverage in Arabic."""
    lines = _header_ar(CLOSURE_VIEW_TITLES["vram-evidence"][1])
    lines.append(f"- القياسات الخارجية المخزَّنة: {_escape(payload.get('measurement_count'))}")
    lines.append(
        "- مُخرجات المجموعة الأساسية ذات قياس خارجي: "
        f"{_escape(payload.get('core_artifacts_with_external_measurement'))}"
    )
    classes = payload.get("source_class_counts", {})
    lines.append(f"- القياسات حسب فئة المصدر: {_escape(classes)}")
    lines.extend(
        [
            "",
            "لا يُنفّذ أطلس أي قياس، ولا يعيد أبداً تسمية قياس على بطاقة أكبر كتحقق على",
            "عتاد الفئة المستهدفة.",
            "",
        ]
    )
    return "\n".join(lines)


def render_retention_en(*, payload: dict) -> str:
    """Render quantization retention coverage in English."""
    lines = _header_en(CLOSURE_VIEW_TITLES["quant-retention"][0])
    rows = payload.get("entries", [])
    if not rows:
        lines.extend([_EMPTY_EN, ""])
        return "\n".join(lines)
    lines.append("| Candidate | Artifact | Quant | Post-training | Retention state |")
    lines.append("|---|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| `{_escape(row['candidate_id'])}` | `{_escape(row['artifact_set_id'])}` | "
            f"{_escape(row.get('quantization'))} | {_escape(row.get('post_training_quantized'))} | "
            f"{_escape(row.get('retention_status'))} |"
        )
    lines.extend(["", "_Generated from canonical machine-readable records._", ""])
    return "\n".join(lines)


def render_retention_ar(*, payload: dict) -> str:
    """Render quantization retention coverage in Arabic."""
    lines = _header_ar(CLOSURE_VIEW_TITLES["quant-retention"][1])
    rows = payload.get("entries", [])
    if not rows:
        lines.extend([_EMPTY_AR, ""])
        return "\n".join(lines)
    lines.append("| المرشّح | المُخرَج | التكميم | بعد التدريب | حالة الاحتفاظ |")
    lines.append("|---|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| `{_escape(row['candidate_id'])}` | `{_escape(row['artifact_set_id'])}` | "
            f"{_escape(row.get('quantization'))} | {_escape(row.get('post_training_quantized'))} | "
            f"{_escape(row.get('retention_status'))} |"
        )
    lines.extend(["", "_مولَّد من سجلات قانونية قابلة للقراءة آلياً._", ""])
    return "\n".join(lines)


def write_view(*, repo_root: Path, view: str, filename: str, text: str) -> Path:
    """Write one generated closure view file."""
    target = repo_root / "catalog" / "views" / "closure" / view / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return target


def write_view_payload(*, repo_root: Path, view: str, payload: dict) -> Path:
    """Write the machine-readable payload for one generated view."""
    target = repo_root / "catalog" / "views" / "closure" / view / "view.json"
    atomic_write_json(target, {"view": view, **payload})
    return target
