"""السجل النسخي للتكميم: عائلات وصيغ موثقة بالمصدر دون ادعاء تكافؤ."""

from __future__ import annotations

# نسخة السجل وتاريخ الرصد المرجعي لجميع الإدخالات أدناه.
REGISTRY_VERSION = "0.2.0"
OBSERVED_AT = "2026-10-05T00:00:00Z"

# مصدر تعريفات GGML وقت التنفيذ: الفرع الرئيسي غير مثبت برقم commit.
_LLAMA_SOURCE = {
    "source_project": "ggml-org/llama.cpp (ggml/include/ggml.h, enum ggml_type)",
    "source_revision": "master branch observed 2026-10-05, GGML_TYPE_COUNT=43 "
    "(unpinned; branch content drifts)",
    "retrieved_at": OBSERVED_AT,
}

# مصدر قيم البت لكل وزن: جدول Quantization Types في توثيق GGUF لدى Hugging Face.
_HF_GGUF_SOURCE = {
    "source_project": "Hugging Face Hub GGUF documentation (Quantization Types table)",
    "source_revision": "docs page observed 2026-10-05 (mutable content, recorded by access date)",
    "retrieved_at": OBSERVED_AT,
}

# العائلات التي يستطيع النظام تمثيلها. القائمة ليست تصريحًا بالتكافؤ.
SUPPORTED_FAMILIES = (
    "f32",
    "f16",
    "bf16",
    "fp8",
    "int8",
    "q8",
    "q6",
    "q5",
    "q4",
    "iq4",
    "q3",
    "iq3",
    "q2",
    "iq2",
    "iq1",
    "q1",
    "tq",
    "ternary",
    "mxfp4",
    "nvfp4",
    "awq",
    "gptq",
    "exl2",
    "mlx",
    "bitsandbytes",
    "other",
    "unknown",
)


def _entry(
    quantization_id: str,
    canonical_name: str,
    family: str,
    *,
    container_format: str | None = None,
    runtime_family: str | None = None,
    nominal_bits: float | None = None,
    effective_bits_per_weight: float | None = None,
    block_size: int | None = None,
    type_size_bytes: int | None = None,
    group_size: int | None = None,
    mixed_precision: bool | None = None,
    native_quantization: bool | None = None,
    weight_only: bool | None = None,
    weight_activation: bool | None = None,
    cache_quantization: bool | None = None,
    aliases: tuple[str, ...] = (),
    source: dict | None = None,
    verification_status: str = "unknown",
    lifecycle: str = "active",
    notes: str | None = None,
) -> dict:
    """بناء إدخال سجل واحد بالحقول الموثقة فقط دون اختراع."""
    return {
        "quantization_id": quantization_id,
        "canonical_name": canonical_name,
        "family": family,
        "container_format": container_format,
        "runtime_family": runtime_family,
        "nominal_bits": nominal_bits,
        "effective_bits_per_weight": effective_bits_per_weight,
        "block_size": block_size,
        "type_size_bytes": type_size_bytes,
        "group_size": group_size,
        "mixed_precision": mixed_precision,
        "native_quantization": native_quantization,
        "weight_only": weight_only,
        "weight_activation": weight_activation,
        "cache_quantization": cache_quantization,
        "aliases": list(aliases),
        "source_project": (source or {}).get("source_project"),
        "source_revision": (source or {}).get("source_revision"),
        "retrieved_at": (source or {}).get("retrieved_at", OBSERVED_AT),
        "verification_status": verification_status,
        "lifecycle": lifecycle,
        "notes": notes,
    }


# الإدخالات المرجعية. قيم bpw المذكورة من مصدر موثق فقط، وإلا تبقى None.
_ENTRIES: tuple[dict, ...] = (
    # الدقة الأصلية غير المكممة لاحقًا.
    _entry(
        "f32",
        "F32",
        "f32",
        container_format=None,
        nominal_bits=32.0,
        effective_bits_per_weight=32.0,
        native_quantization=True,
        verification_status="source_reported",
        notes="دقة أصلية، ليست تكميمًا لاحقًا.",
    ),
    _entry(
        "f16",
        "F16",
        "f16",
        container_format=None,
        nominal_bits=16.0,
        effective_bits_per_weight=16.0,
        native_quantization=True,
        verification_status="source_reported",
        notes="دقة أصلية، ليست تكميمًا لاحقًا.",
    ),
    _entry(
        "bf16",
        "BF16",
        "bf16",
        container_format=None,
        nominal_bits=16.0,
        effective_bits_per_weight=16.0,
        native_quantization=True,
        verification_status="source_reported",
        notes="دقة أصلية؛ ملف BF16 داخل GGUF حاوية لا تكميم.",
    ),
    _entry(
        "fp8",
        "FP8",
        "fp8",
        container_format=None,
        nominal_bits=8.0,
        effective_bits_per_weight=None,
        native_quantization=None,
        verification_status="unknown",
        notes="عائلة تمثيلية فقط؛ الصيغة الدقيقة (E4M3/E5M2) تتطلب دليلًا.",
    ),
    _entry(
        "int8",
        "INT8",
        "int8",
        container_format=None,
        nominal_bits=8.0,
        effective_bits_per_weight=None,
        native_quantization=None,
        verification_status="unknown",
        notes="عائلة تمثيلية فقط دون ادعاء bpw موحد.",
    ),
    # الأنواع القديمة ذات الكتل المحسوبة من التعريف الرسمي للكتلة.
    _entry(
        "ggml-q4-0",
        "Q4_0",
        "q4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=4.5,
        block_size=32,
        type_size_bytes=18,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q4_0",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        lifecycle="legacy",
        notes="كتلة 32 وزنًا: مقياس fp16 مع 16 بايت كميات؛ 18*8/32=4.5.",
    ),
    _entry(
        "ggml-q4-1",
        "Q4_1",
        "q4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=5.0,
        block_size=32,
        type_size_bytes=20,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q4_1",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        lifecycle="legacy",
        notes="كتلة 32 وزنًا مع حد أدنى إضافي؛ 20*8/32=5.0.",
    ),
    _entry(
        "ggml-q5-0",
        "Q5_0",
        "q5",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=5.0,
        effective_bits_per_weight=5.5,
        block_size=32,
        type_size_bytes=22,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q5_0",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        lifecycle="legacy",
        notes="كتلة 32 وزنًا؛ 22*8/32=5.5.",
    ),
    _entry(
        "ggml-q5-1",
        "Q5_1",
        "q5",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=5.0,
        effective_bits_per_weight=6.0,
        block_size=32,
        type_size_bytes=24,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q5_1",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        lifecycle="legacy",
        notes="كتلة 32 وزنًا مع حد أدنى؛ 24*8/32=6.0.",
    ),
    _entry(
        "ggml-q8-0",
        "Q8_0",
        "q8",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=8.0,
        effective_bits_per_weight=8.5,
        block_size=32,
        type_size_bytes=34,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q8_0",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        lifecycle="legacy",
        notes="كتلة 32 وزنًا؛ 34*8/32=8.5. ليست 8.0 بت.",
    ),
    # عائلة K-quants: القيم من جدول توثيق GGUF.
    _entry(
        "ggml-q2-k",
        "Q2_K",
        "q2",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=2.0,
        effective_bits_per_weight=2.625,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q2_k",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="كتل عملاقة 16×16؛ ليست 2.0 بت.",
    ),
    _entry(
        "ggml-q3-k",
        "Q3_K",
        "q3",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=3.0,
        effective_bits_per_weight=3.4375,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q3_k",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="ليست 3.0 بت.",
    ),
    _entry(
        "ggml-q4-k",
        "Q4_K",
        "q4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=4.5,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q4_k",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="النوع الأساسي؛ المتغيرات المسماة (_M/_S) مختلطة الدقة.",
    ),
    _entry(
        "ggml-q5-k",
        "Q5_K",
        "q5",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=5.0,
        effective_bits_per_weight=5.5,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q5_k",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="ليست 5.0 بت.",
    ),
    _entry(
        "ggml-q6-k",
        "Q6_K",
        "q6",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=6.0,
        effective_bits_per_weight=6.5625,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q6_k",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="ليست 6.0 بت.",
    ),
    _entry(
        "ggml-q8-k",
        "Q8_K",
        "q8",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=8.0,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q8_k",),
        source=_LLAMA_SOURCE,
        verification_status="unknown",
        notes="تستخدم للنتائج الوسيطة غالبًا؛ bpw تتطلب حساب الكتلة الرسمي.",
    ),
    # متغيرات K المسماة: مختلطة الدقة ولا تحمل bpw مفردًا.
    _entry(
        "ggml-q4-k-m",
        "Q4_K_M",
        "q4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=None,
        mixed_precision=True,
        native_quantization=False,
        weight_only=True,
        aliases=("q4_k_m", "q4km"),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="مزيج موثق لكل نوع موتر؛ لا تختزل إلى 4.0 أو 4.5 بت.",
    ),
    _entry(
        "ggml-q4-k-s",
        "Q4_K_S",
        "q4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=None,
        mixed_precision=True,
        native_quantization=False,
        weight_only=True,
        aliases=("q4_k_s",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="مزيج موثق لكل نوع موتر؛ تختلف عن Q4_K_M.",
    ),
    _entry(
        "ggml-q5-k-m",
        "Q5_K_M",
        "q5",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=5.0,
        effective_bits_per_weight=None,
        mixed_precision=True,
        native_quantization=False,
        weight_only=True,
        aliases=("q5_k_m",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="مزيج موثق لكل نوع موتر.",
    ),
    _entry(
        "ggml-q5-k-s",
        "Q5_K_S",
        "q5",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=5.0,
        effective_bits_per_weight=None,
        mixed_precision=True,
        native_quantization=False,
        weight_only=True,
        aliases=("q5_k_s",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="مزيج موثق لكل نوع موتر.",
    ),
    _entry(
        "ggml-q3-k-m",
        "Q3_K_M",
        "q3",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=3.0,
        effective_bits_per_weight=None,
        mixed_precision=True,
        native_quantization=False,
        weight_only=True,
        aliases=("q3_k_m",),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="مزيج موثق لكل نوع موتر.",
    ),
    _entry(
        "ggml-q6-k-generic",
        "Q6_K",
        "q6",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=6.0,
        effective_bits_per_weight=6.5625,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q6_k",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="إدخال النوع الأساسي؛ المتغيرات المسماة إن وجدت مختلطة.",
    ),
    # عائلة IQ: القيم من جدول توثيق GGUF حيث ذكرت.
    _entry(
        "ggml-iq2-xxs",
        "IQ2_XXS",
        "iq2",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=2.0,
        effective_bits_per_weight=2.06,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq2_xxs",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="تعتمد مصفوفة الأهمية؛ ليست 2.0 بت.",
    ),
    _entry(
        "ggml-iq2-xs",
        "IQ2_XS",
        "iq2",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=2.0,
        effective_bits_per_weight=2.31,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq2_xs",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="تعتمد مصفوفة الأهمية.",
    ),
    _entry(
        "ggml-iq2-s",
        "IQ2_S",
        "iq2",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=2.0,
        effective_bits_per_weight=2.5,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq2_s",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="تعتمد مصفوفة الأهمية.",
    ),
    _entry(
        "ggml-iq2-m",
        "IQ2_M",
        "iq2",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=2.0,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq2_m",),
        source=_LLAMA_SOURCE,
        verification_status="unknown",
        notes="النوع موجود في التعداد الرسمي دون قيمة bpw موثقة في الجدول.",
    ),
    _entry(
        "ggml-iq3-xxs",
        "IQ3_XXS",
        "iq3",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=3.0,
        effective_bits_per_weight=3.06,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq3_xxs",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="تعتمد مصفوفة الأهمية.",
    ),
    _entry(
        "ggml-iq3-s",
        "IQ3_S",
        "iq3",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=3.0,
        effective_bits_per_weight=3.44,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq3_s",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="تعتمد مصفوفة الأهمية.",
    ),
    _entry(
        "ggml-iq4-nl",
        "IQ4_NL",
        "iq4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq4_nl",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="كتل عملاقة 256 وزنًا مع مصفوفة أهمية؛ bpw يتطلب مخزون موترات.",
    ),
    _entry(
        "ggml-iq4-xs",
        "IQ4_XS",
        "iq4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=4.25,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq4_xs",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="تعتمد مصفوفة الأهمية.",
    ),
    _entry(
        "ggml-iq1-s",
        "IQ1_S",
        "iq1",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=1.0,
        effective_bits_per_weight=1.56,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq1_s",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="ليست 1.0 بت.",
    ),
    _entry(
        "ggml-iq1-m",
        "IQ1_M",
        "iq1",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=1.0,
        effective_bits_per_weight=1.75,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("iq1_m",),
        source=_HF_GGUF_SOURCE,
        verification_status="source_reported",
        notes="ليست 1.0 بت.",
    ),
    # التكميم الثلاثي.
    _entry(
        "ggml-tq1-0",
        "TQ1_0",
        "tq",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("tq1_0", "tq1"),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="تكميم ثلاثي؛ يختلف عن النماذج الثلاثية الأصلية التدريب.",
    ),
    _entry(
        "ggml-tq2-0",
        "TQ2_0",
        "tq",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("tq2_0", "tq2"),
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="تكميم ثلاثي؛ يختلف عن النماذج الثلاثية الأصلية التدريب.",
    ),
    _entry(
        "native-ternary",
        "Ternary-Native",
        "ternary",
        container_format=None,
        runtime_family=None,
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=True,
        weight_only=None,
        source=None,
        verification_status="unknown",
        notes="نموذج مدرب ثلاثيًا أصالة وفق دليل؛ ليس صيغة TQ.",
    ),
    # بت واحد وبتان الجديدان في التعداد الرسمي.
    _entry(
        "ggml-q1-0",
        "Q1_0",
        "q1",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=1.0,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q1_0",),
        source=_LLAMA_SOURCE,
        verification_status="unknown",
        notes="موجود في التعداد الرسمي دون bpw موثقة.",
    ),
    _entry(
        "ggml-q2-0",
        "Q2_0",
        "q2",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=2.0,
        effective_bits_per_weight=None,
        mixed_precision=False,
        native_quantization=False,
        weight_only=True,
        aliases=("q2_0",),
        source=_LLAMA_SOURCE,
        verification_status="unknown",
        notes="موجود في التعداد الرسمي دون bpw موثقة.",
    ),
    # MXFP4 وNVFP4 صيغتان مختلفتان.
    _entry(
        "mxfp4",
        "MXFP4",
        "mxfp4",
        container_format="GGUF",
        runtime_family="llama.cpp",
        nominal_bits=4.0,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=False,
        weight_only=True,
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="كتلة microscaling واحدة؛ الدعم يعتمد على الجيل والنواة.",
    ),
    _entry(
        "nvfp4",
        "NVFP4",
        "nvfp4",
        container_format=None,
        runtime_family="tensorrt-llm",
        nominal_bits=4.0,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=False,
        weight_only=None,
        source=_LLAMA_SOURCE,
        verification_status="source_reported",
        notes="أربع كتل بمقياس E4M3؛ ليست مرادفًا لـMXFP4.",
    ),
    # العائلات المستقلة: AWQ وGPTQ وEXL2 وMLX وbitsandbytes.
    _entry(
        "awq-generic",
        "AWQ",
        "awq",
        container_format="safetensors",
        runtime_family=None,
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=False,
        weight_only=True,
        source=None,
        verification_status="unknown",
        notes="تحددها structured config ‏(quant_method/bits/group_size)‏ لا الاسم.",
    ),
    _entry(
        "gptq-generic",
        "GPTQ",
        "gptq",
        container_format="safetensors",
        runtime_family=None,
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=False,
        weight_only=True,
        source=None,
        verification_status="unknown",
        notes="خوارزمية مستقلة؛ ليست كل نسخ 4-bit متماثلة.",
    ),
    _entry(
        "exl2-generic",
        "EXL2",
        "exl2",
        container_format=None,
        runtime_family="exllamav2",
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=True,
        native_quantization=False,
        weight_only=True,
        source=None,
        verification_status="unknown",
        notes="مزج مستويات للوصول إلى bitrate مستهدف؛ تسجل target_bpw/effective_bpw.",
    ),
    _entry(
        "mlx-generic",
        "MLX-Quant",
        "mlx",
        container_format=None,
        runtime_family="mlx-lm",
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=False,
        weight_only=None,
        source=None,
        verification_status="unknown",
        notes="أساليب متعددة (affine/dynamic/AWQ/GPTQ)؛ تسجل الطريقة نفسها.",
    ),
    _entry(
        "bnb-generic",
        "bitsandbytes",
        "bitsandbytes",
        container_format=None,
        runtime_family="transformers",
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=False,
        weight_only=None,
        source=None,
        verification_status="unknown",
        notes="عائلة تمثيلية دون ادعاء bpw موحد.",
    ),
    _entry(
        "other-generic",
        "Other-Quant",
        "other",
        container_format=None,
        runtime_family=None,
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=None,
        weight_only=None,
        source=None,
        verification_status="unknown",
        notes="صيغة موثقة خارج العائلات المعروفة؛ تسجل بذاتها لا بالتخمين.",
    ),
    _entry(
        "unknown-quant",
        "Unknown",
        "unknown",
        container_format=None,
        runtime_family=None,
        nominal_bits=None,
        effective_bits_per_weight=None,
        mixed_precision=None,
        native_quantization=None,
        weight_only=None,
        source=None,
        verification_status="unknown",
        notes="غياب الدليل يبقى unknown ولا يتحول إلى رقم.",
    ),
)

# فهرس الأسماء والأسماء البديلة إلى الإدخال المعياري.
_ALIAS_INDEX: dict[str, dict] = {}
for _item in _ENTRIES:
    _ALIAS_INDEX[_item["canonical_name"].upper()] = _item
    _ALIAS_INDEX[_item["quantization_id"].upper()] = _item
    for _alias in _item["aliases"]:
        _ALIAS_INDEX.setdefault(_alias.upper(), _item)


def list_entries(*, family: str | None = None, lifecycle: str | None = None) -> list[dict]:
    """سرد الإدخالات مع ترشيح اختياري بالعائلة أو دورة الحياة."""
    result = list(_ENTRIES)
    if family is not None:
        result = [item for item in result if item["family"] == family]
    if lifecycle is not None:
        result = [item for item in result if item["lifecycle"] == lifecycle]
    return result


def find_entry(name: str | None) -> dict | None:
    """البحث عن إدخال بالاسم المعياري أو البديل دون إنشاء مدخلات مكررة."""
    if not name or not isinstance(name, str):
        return None
    return _ALIAS_INDEX.get(name.strip().upper())


def resolve_alias(name: str | None) -> str | None:
    """إرجاع الاسم المعياري للبديل أو None عند غياب الدليل."""
    found = find_entry(name)
    return found["canonical_name"] if found else None


def get_alias_target(name: str | None) -> dict | None:
    """إرجاع الإدخال المعياري للبديل مع الحفاظ على فصل البديل عن الأصل."""
    return find_entry(name)
