"""Generated quality views, EN/AR from one canonical dataset.

Views derive from quality records only; no hand-maintained table exists.
English and Arabic render from the same payload so rankings can never diverge.
Empty views are acceptable and are written as explicitly empty.
"""

from __future__ import annotations

from pathlib import Path

from atlas.intake.store import atomic_write_json

GENERATED_MARKER_EN = (
    "<!-- GENERATED BY ATLAS QUALITY PIPELINE — DO NOT EDIT BY HAND. "
    "Regenerate via `atlas quality views`. -->"
)
GENERATED_MARKER_AR = (
    "<!-- مُوَلَّد بواسطة خط أنابيب الجودة في أطلس — لا تحرر يدويًا. "
    "أعد التوليد عبر `atlas quality views`. -->"
)

# view slug -> (EN title, AR title)
VIEW_TITLES = {
    "general-quality": ("General Quality", "الجودة العامة"),
    "coding": ("Coding Quality", "جودة البرمجة"),
    "reasoning": ("Reasoning Quality", "جودة الاستدلال"),
    "agentic-tool-use": ("Agentic / Tool Use", "القدرة على استخدام الأدوات"),
    "high-compression": ("High Compression", "الضغط العالي"),
    "native-low-bit": ("Native Low-Bit", "النماذج منخفضة البت الأصلية"),
    "ternary": ("Ternary Models", "النماذج الثلاثية"),
    "uncensored": ("Uncensored / Alignment Variants", "المتغيرات غير المقيدة"),
    "quality-gaps": ("Evidence Gaps", "فجوات الأدلة"),
}

_EMPTY_NOTE_EN = (
    "_No entries: Atlas found no defensible evidence for this view yet. "
    "An empty view is an honest state, not an error._"
)
_EMPTY_NOTE_AR = (
    "_لا توجد عناصر: لم يعثر أطلس على أدلة قابلة للدفاع عن هذا العرض بعد. "
    "العرض الفارغ حالة صادقة لا خطأ._"
)


def _header_en(title: str) -> list[str]:
    return [
        GENERATED_MARKER_EN,
        f"# {title}",
        "",
        "> Derived from canonical quality records. Missing evidence is reported as unknown;",
        "> popularity, size, recency and publisher brand never influence these views.",
        "",
    ]


def _header_ar(title: str) -> list[str]:
    return [
        GENERATED_MARKER_AR,
        f"# {title}",
        "",
        "> مشتق من سجلات الجودة المعيارية. الأدلة الناقصة تُعرض كـ«غير معروف»؛",
        "> الشعبية والحجم وحداثة الإصدار وسمعة الناشر لا تؤثر في هذه العروض إطلاقًا.",
        "",
    ]


def render_axis_view_en(*, view: str, rows: list[dict]) -> str:
    """Render an axis view in English from one canonical payload."""
    title = VIEW_TITLES[view][0]
    lines = _header_en(title)
    if not rows:
        lines.append(_EMPTY_NOTE_EN)
        lines.append("")
        return "\n".join(lines)
    lines.append("| Model | Evidence status | Evaluations | Note |")
    lines.append("|---|---|---|---|")
    for row in rows:
        note = (row.get("note") or "").replace("|", "/")
        lines.append(
            f"| `{row['model_id']}` | {row.get('evidence_status')} | "
            f"{row.get('evaluation_count')} | {note} |"
        )
    lines.append("")
    lines.append("_Generated from canonical machine-readable records._")
    lines.append("")
    return "\n".join(lines)


def render_axis_view_ar(*, view: str, rows: list[dict]) -> str:
    """Render an axis view in Arabic (MSA) from the same payload."""
    title = VIEW_TITLES[view][1]
    lines = _header_ar(title)
    if not rows:
        lines.append(_EMPTY_NOTE_AR)
        lines.append("")
        return "\n".join(lines)
    lines.append("| النموذج | حالة الأدلة | عدد التقييمات | ملاحظة |")
    lines.append("|---|---|---|---|")
    for row in rows:
        note = (row.get("note_ar") or row.get("note") or "").replace("|", "/")
        status = row.get("evidence_status_ar") or row.get("evidence_status")
        lines.append(f"| `{row['model_id']}` | {status} | {row.get('evaluation_count')} | {note} |")
    lines.append("")
    lines.append("_مُوَلَّد من السجلات المعيارية القابلة للقراءة آليًا._")
    lines.append("")
    return "\n".join(lines)


def render_tier_view_en(*, tier_gb: int, payload: dict) -> str:
    """Per-tier recommendation readiness, English, categories never merged."""
    lines = _header_en(f"{tier_gb}GB VRAM — Recommendation Readiness")
    counts = payload.get("counts", {})
    lines.append(f"- Strict evidence-backed recommendations: **{counts.get('eligible', 0)}**")
    lines.append(
        f"- Promising candidates — fit evidence incomplete: **{counts.get('candidate', 0)}**"
    )
    lines.append(
        f"- Fit candidates — quality evidence incomplete: "
        f"**{counts.get('fit_known_quality_unknown', 0)}**"
    )
    lines.append(f"- Insufficient evidence: **{counts.get('insufficient_evidence', 0)}**")
    lines.append("")
    for key, heading in (
        ("strict", "Strict Evidence-Backed Recommendations"),
        ("candidates", "Promising Candidates — Fit Evidence Incomplete"),
        ("fit_known_quality_unknown", "Fit Candidates — Quality Evidence Incomplete"),
        ("insufficient", "Insufficient Evidence"),
    ):
        entries = payload.get(key, [])
        lines.append(f"## {heading} ({len(entries)})")
        lines.append("")
        if not entries:
            lines.append("_None._")
            lines.append("")
            continue
        for entry in entries:
            lines.append(
                f"- `{entry['model_id']}` — confidence `{entry.get('confidence_state')}`; "
                f"fit `{entry.get('domains', {}).get('vram_fit', {}).get('state')}`; "
                f"quality `{entry.get('domains', {}).get('quality', {}).get('status')}`"
            )
        lines.append("")
    lines.append(
        "_Categories are never merged, and zero strict recommendations is reported "
        "honestly rather than backfilled._"
    )
    lines.append("")
    return "\n".join(lines)


def render_tier_view_ar(*, tier_gb: int, payload: dict) -> str:
    """Per-tier recommendation readiness, Arabic, same canonical payload."""
    lines = _header_ar(f"ذاكرة {tier_gb} غيغابايت — جاهزية التوصيات")
    counts = payload.get("counts", {})
    lines.append(f"- توصيات صارمة مدعومة بالأدلة: **{counts.get('eligible', 0)}**")
    lines.append(f"- مرشحون واعدون — أدلة الملاءمة غير مكتملة: **{counts.get('candidate', 0)}**")
    lines.append(
        f"- مرشحون من حيث الملاءمة — أدلة الجودة غير مكتملة: "
        f"**{counts.get('fit_known_quality_unknown', 0)}**"
    )
    lines.append(f"- أدلة غير كافية: **{counts.get('insufficient_evidence', 0)}**")
    lines.append("")
    for key, heading in (
        ("strict", "توصيات صارمة مدعومة بالأدلة"),
        ("candidates", "مرشحون واعدون — أدلة الملاءمة غير مكتملة"),
        ("fit_known_quality_unknown", "مرشحون من حيث الملاءمة — أدلة الجودة غير مكتملة"),
        ("insufficient", "أدلة غير كافية"),
    ):
        entries = payload.get(key, [])
        lines.append(f"## {heading} ({len(entries)})")
        lines.append("")
        if not entries:
            lines.append("_لا يوجد._")
            lines.append("")
            continue
        for entry in entries:
            domains = entry.get("domains", {})
            lines.append(
                f"- `{entry['model_id']}` — درجة الإسناد `{entry.get('confidence_state')}`؛ "
                f"الملاءمة `{domains.get('vram_fit', {}).get('state')}`؛ "
                f"الجودة `{domains.get('quality', {}).get('status')}`"
            )
        lines.append("")
    lines.append(
        "_لا تُدمج الفئات معًا أبدًا، ويذكر عدد التوصيات الصارمة البالغ صفرًا بصدق دون "
        "استبداله بمرشحين أضعف._"
    )
    lines.append("")
    return "\n".join(lines)


def quality_views_dir(repo_root: Path) -> Path:
    """Canonical quality view output directory."""
    return repo_root / "catalog" / "views" / "quality"


def write_view(repo_root: Path, *, view: str, text: str, filename: str = "index.md") -> Path:
    """Write one generated view file (atomic, deterministic name)."""
    base = quality_views_dir(repo_root)
    target = base / view / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(target)
    return target


def write_view_payload(repo_root: Path, *, view: str, payload: dict) -> Path:
    """Write the machine-readable companion payload for a generated view."""
    target = quality_views_dir(repo_root) / view / "view.json"
    atomic_write_json(target, payload)
    return target


def write_index(repo_root: Path, *, entries: list[dict], lang: str) -> Path:
    """Write the EN/AR quality view index from one payload."""
    base = quality_views_dir(repo_root)
    target = base / f"index.{lang}.md"
    if lang == "ar":
        lines = [GENERATED_MARKER_AR, "# عروض الجودة في أطلس", "", "| العرض | الوصف |", "|---|---|"]
        for entry in entries:
            lines.append(f"| `{entry['view']}` | {entry['title']} |")
    else:
        lines = [
            GENERATED_MARKER_EN,
            "# Atlas Quality Views",
            "",
            "| View | Description |",
            "|---|---|",
        ]
        for entry in entries:
            lines.append(f"| `{entry['view']}` | {entry['title']} |")
    lines.append("")
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".tmp")
    tmp.write_text("\n".join(lines), encoding="utf-8")
    tmp.replace(target)
    return target
