"""Generated catalog views + bilingual EN/AR indexes (Phase 4).

Same canonical data drives English and Arabic outputs. Deterministic
ordering; timestamps only where documented (generated_at). Generated
files carry markers and must never be hand-edited.
"""

from __future__ import annotations

GENERATED_MARKER_EN = (
    "<!-- GENERATED BY ATLAS CATALOG PIPELINE — DO NOT EDIT BY HAND. "
    "Regenerate via `atlas catalog views`. -->"
)
GENERATED_MARKER_AR = (
    "<!-- مُوَلَّد بواسطة خط أنابيب كتالوج أطلس — لا تحرر يدويًا. "
    "أعد التوليد عبر `atlas catalog views`. -->"
)

TIER_SECTIONS = (
    "verified_fit",
    "estimated_fit",
    "indeterminate_fit",
    "estimated_not_fit",
    "verified_not_fit",
    "insufficient_evidence",
    "unsupported",
)


def _sorted_ids(ids: list[str]) -> list[str]:
    return sorted(set(ids))


def build_tier_view_payload(
    *,
    tier_gb: int,
    classifications: dict[str, dict],
    records: dict[str, dict],
) -> dict:
    """Machine-readable tier payload with explicit fit-state sections."""
    sections: dict[str, list[dict]] = {s: [] for s in TIER_SECTIONS}
    # Also accept states produced by classifier subset.
    extra_states: dict[str, list[dict]] = {}
    for model_id in sorted(classifications):
        cls = classifications[model_id]
        state = str(cls.get("by_tier", {}).get(str(tier_gb), "insufficient_evidence"))
        rec = records.get(model_id, {})
        entry = {
            "model_id": model_id,
            "display_name": rec.get("display_name"),
            "state": state,
            "estimate_status": cls.get("estimate_status"),
            "lower_bytes": cls.get("lower_bytes"),
            "upper_bytes": cls.get("upper_bytes"),
        }
        if state in sections:
            sections[state].append(entry)
        else:
            extra_states.setdefault(state, []).append(entry)
    sections.update(extra_states)
    return {
        "tier_gb": tier_gb,
        "generated_note": "Strict VRAM view: sections are fit states, never merged.",
        "sections": sections,
    }


def render_tier_markdown_en(*, tier_gb: int, payload: dict) -> str:
    """Render English tier page with honest section language."""
    lines = [
        GENERATED_MARKER_EN,
        f"# {tier_gb}GB VRAM Atlas",
        "",
        "> Qualified means Atlas holds enough trustworthy metadata to include "
        "the model under current catalog rules. It does not mean recommended, "
        "safe, fastest, or fully VRAM-verified.",
        "> File size alone never proves VRAM fit.",
        "",
    ]
    sections = payload.get("sections", {})
    for state in sorted(sections):
        entries = sections[state]
        lines.append(f"## {state} ({len(entries)})")
        lines.append("")
        if not entries:
            lines.append("_No entries in this state._")
            lines.append("")
            continue
        for e in entries:
            lines.append(f"- `{e['model_id']}` — {e.get('display_name') or ''}".rstrip())
        lines.append("")
    lines.append("_Generated from canonical machine-readable records._")
    lines.append("")
    return "\n".join(lines)


def render_tier_markdown_ar(*, tier_gb: int, payload: dict) -> str:
    """Render Arabic tier page (Modern Standard Arabic, technical terms kept)."""
    lines = [
        GENERATED_MARKER_AR,
        f"# أطلس VRAM بسعة {tier_gb}GB",
        "",
        "> «مؤهَّل» تعني أن أطلس يملك بيانات وصفية موثوقة كافية لإدراج النموذج "
        "وفق قواعد الكتالوج الحالية. ولا تعني موصى به أو آمن أو أسرع أو متحققًا "
        "بالكامل من VRAM.",
        "> حجم الملف وحده لا يثبت أبدًا توافق VRAM.",
        "",
    ]
    sections = payload.get("sections", {})
    for state in sorted(sections):
        entries = sections[state]
        lines.append(f"## {state} ({len(entries)})")
        lines.append("")
        if not entries:
            lines.append("_لا توجد إدخالات في هذه الحالة._")
            lines.append("")
            continue
        for e in entries:
            lines.append(f"- `{e['model_id']}` — {e.get('display_name') or ''}".rstrip())
        lines.append("")
    lines.append("_مُوَلَّد من السجلات المعيارية المقروءة آليًا._")
    lines.append("")
    return "\n".join(lines)


def build_special_view_payload(
    *, view_id: str, model_ids: list[str], records: dict[str, dict], note: str
) -> dict:
    """Machine-readable special-view payload (deterministic order)."""
    entries = []
    for mid in _sorted_ids(model_ids):
        rec = records.get(mid, {})
        entries.append(
            {
                "model_id": mid,
                "display_name": rec.get("display_name"),
                "quantization": rec.get("quantization"),
                "alignment": rec.get("alignment"),
            }
        )
    return {"view_id": view_id, "note": note, "count": len(entries), "entries": entries}


def render_special_markdown_en(*, title: str, payload: dict, disclaimer: str) -> str:
    """Render English special-view page."""
    lines = [GENERATED_MARKER_EN, f"# {title}", "", f"> {disclaimer}", ""]
    for e in payload.get("entries", []):
        lines.append(f"- `{e['model_id']}` — {e.get('display_name') or ''}".rstrip())
    if not payload.get("entries"):
        lines.append("_No entries with sufficient evidence._")
    lines.append("")
    lines.append("_Generated from canonical machine-readable records._")
    lines.append("")
    return "\n".join(lines)


def render_special_markdown_ar(*, title: str, payload: dict, disclaimer: str) -> str:
    """Render Arabic special-view page."""
    lines = [GENERATED_MARKER_AR, f"# {title}", "", f"> {disclaimer}", ""]
    for e in payload.get("entries", []):
        lines.append(f"- `{e['model_id']}` — {e.get('display_name') or ''}".rstrip())
    if not payload.get("entries"):
        lines.append("_لا توجد إدخالات بأدلة كافية._")
    lines.append("")
    lines.append("_مُوَلَّد من السجلات المعيارية المقروءة آليًا._")
    lines.append("")
    return "\n".join(lines)


def render_index_markdown_en(*, stats: dict, model_ids: list[str]) -> str:
    """Render English catalog index."""
    lines = [
        GENERATED_MARKER_EN,
        "# Local LLM VRAM Atlas — Catalog Index",
        "",
        "> Initial curated, metadata-only catalog snapshot with provenance, "
        "license/openness classification and conservative VRAM classification. "
        "Not exhaustive. Qualified does not mean recommended.",
        "",
        f"Models: {stats.get('model_count')} | "
        f"Artifact variants: {stats.get('artifact_count')} | "
        f"Qualified: {stats.get('qualified')} | "
        f"With limitations: {stats.get('qualified_with_limitations')}",
        "",
        "## Models",
        "",
    ]
    for mid in _sorted_ids(model_ids):
        lines.append(f"- `{mid}`")
    lines.append("")
    return "\n".join(lines)


def render_index_markdown_ar(*, stats: dict, model_ids: list[str]) -> str:
    """Render Arabic catalog index."""
    lines = [
        GENERATED_MARKER_AR,
        "# أطلس نماذج اللغة المحلية — فهرس الكتالوج",
        "",
        "> لقطة أولية منتقاة من الكتالوج بالبيانات الوصفية فقط، مع النسب "
        "وتصنيف الترخيص/الانفتاح وتصنيف VRAM متحفظ. ليست شاملة. "
        "«مؤهَّل» لا تعني «موصى به».",
        "",
        f"النماذج: {stats.get('model_count')} | "
        f"متغيرات Artifacts: {stats.get('artifact_count')} | "
        f"مؤهلة: {stats.get('qualified')} | "
        f"بقيود: {stats.get('qualified_with_limitations')}",
        "",
        "## النماذج",
        "",
    ]
    for mid in _sorted_ids(model_ids):
        lines.append(f"- `{mid}`")
    lines.append("")
    return "\n".join(lines)
